# Generated by Django 4.1.7 on 2023-03-28 04:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(8, message='Password must have at least 8 characters.'), django.core.validators.MaxLengthValidator(15, message='password must have at most 15 characters.')]),
        ),
    ]
