# Generated by Django 4.1.7 on 2023-03-28 05:01

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_alter_barber_password_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='Parvaneh',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10, message='Parvaneh No. must be 10 numbers'), django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message='Parvaneh No. is not  valid.')]),
        ),
        migrations.AlterField(
            model_name='barber',
            name='phone_Number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11, message='Phone No. must have 11 numeric characters.'), django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message='phone No. is not valid')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_Number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11, message='Phone No. must have 11 numeric characters.'), django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message='phone No. is not valid')]),
        ),
    ]
