# Generated by Django 4.1.7 on 2023-03-28 07:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_alter_barber_parvaneh_alter_barber_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='Parvaneh',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10, message='Parvaneh No. must be 10 numbers')]),
        ),
        migrations.AlterField(
            model_name='barber',
            name='phone_Number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11, message='Phone No. must have 11 numeric characters.')]),
        ),
    ]
