# Generated by Django 4.1.7 on 2023-03-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_alter_barber_parvaneh_alter_barber_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='Parvaneh',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='barber',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='barber',
            name='phone_Number',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_Number',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
