# Generated by Django 4.1.7 on 2023-03-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("accounts", "0005_barber_customer_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="barber",
            name="groups",
            field=models.ManyToManyField(related_name="barber_groups", to="auth.group"),
        ),
        migrations.AddField(
            model_name="barber",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AddField(
            model_name="barber",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="barber",
            name="password",
            field=models.CharField(default=" ", max_length=255),
        ),
        migrations.AddField(
            model_name="barber",
            name="user_permissions",
            field=models.ManyToManyField(
                related_name="barber_user_permissions", to="auth.permission"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="groups",
            field=models.ManyToManyField(
                related_name="customer_groups", to="auth.group"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="password",
            field=models.CharField(default=" ", max_length=255),
        ),
        migrations.AddField(
            model_name="customer",
            name="user_permissions",
            field=models.ManyToManyField(
                related_name="customer_user_permissions", to="auth.permission"
            ),
        ),
    ]
