# Generated by Django 4.1.7 on 2023-03-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0006_barber_groups_barber_is_superuser_barber_last_login_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="barber",
            name="phone_Number",
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], max_length=6
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone_Number",
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
