# Generated by Django 4.1.7 on 2023-03-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_barber_phone_number_alter_customer_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone_Number",
            field=models.CharField(max_length=11),
        ),
    ]
