# Generated by Django 4.1.7 on 2023-03-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_customer_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], max_length=6
            ),
        ),
    ]
