# Generated by Django 4.1.7 on 2023-03-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_customer_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="phone_Number",
            field=models.CharField(default=" ", max_length=11),
        ),
    ]
