# Generated by Django 4.1.7 on 2023-03-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_remove_barber_email_remove_customer_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="barber",
            name="email",
            field=models.EmailField(default=" ", max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(default=" ", max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="first_name",
            field=models.CharField(default=" ", max_length=255),
        ),
        migrations.AddField(
            model_name="customer",
            name="last_name",
            field=models.CharField(default=" ", max_length=255),
        ),
        migrations.AlterField(
            model_name="barber",
            name="password",
            field=models.CharField(default=" ", max_length=255),
        ),
        migrations.AlterField(
            model_name="customer",
            name="password",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
