# Generated by Django 4.2 on 2023-04-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_remove_barber_region_remove_customer_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/default_profile.png', error_messages={'invalid': 'Image files only'}, null=True, upload_to='profile_pictures/'),
        ),
    ]
