# Generated by Django 4.2 on 2023-05-23 06:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BarberShop', models.CharField(max_length=255)),
                ('Owner', models.CharField(max_length=255)),
                ('Parvaneh', models.CharField(max_length=10, null=True, unique=True)),
                ('phone_Number', models.CharField(max_length=11, null=True, unique=True)),
                ('area', models.CharField(choices=[('Tehranpars', 'Tehranpars'), ('Nazi Abad', 'Nazi Abad'), ('Narmak', 'Narmak'), ('Tajrish', 'Tajrish'), ('Gheytariye', 'Gheytariye'), ('Marzdaran', 'Marzdaran'), ('Janat Abad', 'Janat Abad'), ('Vanak', 'Vanak'), ('Enghelab', 'Enghelab'), ('Valiasr', 'Valiasr'), ('Saadat Abad', 'Saadat Abad'), ('Piroozi', 'Piroozi'), ('Jordan', 'Jordan')], max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('rate', models.FloatField(default=1)),
                ('background', models.ImageField(default='default_profile.png', upload_to='Barber/backg')),
                ('logo', models.ImageField(default='default_profile.png', upload_to='Barber/Logo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('barber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='Barber.barber')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('servicePic', models.ImageField(default='default_profile.png', null=True, upload_to='Barber/Service')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryServices', to='Barber.category')),
            ],
        ),
        migrations.CreateModel(
            name='BarberDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=256)),
                ('img', models.ImageField(default='default_profile.png', upload_to='Barber/Description')),
                ('barber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barberDesc', to='Barber.barber')),
            ],
        ),
        migrations.CreateModel(
            name='OrderServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('ordering', 'ordering'), ('paid', 'paid'), ('BarberCancelled', 'BarberCancelled'), ('CustomerCancelled', 'CustomerCancelled'), ('CustomerNotCome', 'CustomerNotCome'), ('Done', 'Done')], default='ordering', max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber', to='Barber.barber')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='Customer.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='Barber.categoryservice')),
            ],
            options={
                'ordering': ['date', 'time'],
                'unique_together': {('barber', 'time', 'date')},
            },
        ),
    ]
