# Generated by Django 4.2 on 2023-05-06 13:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_alter_customer_credit'),
        ('Barber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('C', 'Credit'), ('O', 'Order')], default='C', max_length=1)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactionCustomer', to='Customer.customer')),
                ('order', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactionsOrder', to='Barber.orderservices')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
