# Generated by Django 4.2 on 2023-04-18 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
        ('Barber', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Barber.barber'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors_comments', to='Customer.customer'),
        ),
    ]
