# Generated by Django 4.1.8 on 2023-04-09 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_customer_profile_picture'),
        ('Barber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Auth.barber')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.customer')),
                ('parent_comment', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Barber.comment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
