# Generated by Django 4.2 on 2023-05-09 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Barber', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='service',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactionService', to='Barber.categoryservice'),
        ),
    ]
