# Generated by Django 4.2 on 2023-05-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barber', '0003_transaction_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='order',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('C', 'Charge'), ('O', 'Order')], default='C', max_length=1),
        ),
    ]
