# Generated by Django 4.2 on 2023-04-25 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Barber', '0003_comment_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
    ]
