# Generated by Django 4.2 on 2023-05-10 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Barber', '0004_remove_transaction_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='service',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactionService', to='Barber.categoryservice'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
