# Generated by Django 4.2 on 2023-05-10 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barber', '0005_alter_transaction_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 10, 16, 49, 45, 879857), null=True),
        ),
    ]
