# Generated by Django 4.2.1 on 2023-07-08 18:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0090_alter_barberpremium_expire_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barberpremium",
            name="expire_date",
            field=models.DateField(default=datetime.date(2023, 8, 8)),
        ),
        migrations.CreateModel(
            name="ServiceGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        default="default_profile.png", upload_to="Barber/Gallery"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Barber.categoryservice",
                    ),
                ),
            ],
        ),
    ]
