# Generated by Django 4.2.1 on 2023-07-08 22:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0091_alter_barberpremium_expire_date_servicegallery"),
    ]

    operations = [
        migrations.AddField(
            model_name="barber",
            name="foundation",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="barber",
            name="gender",
            field=models.CharField(
                choices=[("Male", "M"), ("Female", "F")], default="M", max_length=6
            ),
        ),
        migrations.AlterField(
            model_name="barberpremium",
            name="expire_date",
            field=models.DateField(default=datetime.date(2023, 8, 9)),
        ),
        migrations.AlterField(
            model_name="orderservices",
            name="status",
            field=models.CharField(
                choices=[
                    ("ordering", "ordering"),
                    ("confirmed", "confirmed"),
                    ("paid", "paid"),
                    ("BarberCancelled", "BarberCancelled"),
                    ("CustomerCancelled", "CustomerCancelled"),
                    ("Done", "Done"),
                ],
                default="ordering",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="servicegallery",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery",
                to="Barber.categoryservice",
            ),
        ),
    ]
