# Generated by Django 4.2.1 on 2023-07-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0092_barber_foundation_barber_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barber",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                default="M",
                max_length=6,
            ),
        ),
    ]
