# Generated by Django 4.2.1 on 2023-07-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0098_alter_barber_gender_alter_barber_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderservices",
            name="status",
            field=models.CharField(
                choices=[
                    ("ordering", "ordering"),
                    ("rejected", "rejected"),
                    ("paid", "paid"),
                    ("CustomerCancelled", "CustomerCancelled"),
                    ("Done", "Done"),
                ],
                default="ordering",
                max_length=20,
            ),
        ),
    ]
